services:
  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8888:8888" # Default Vite port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge